project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - about.qmd
    - Avancee.qmd
    - Departements/Ariege.qmd
    - Departements/Aude.qmd
    - Departements/Aveyron.qmd
    - Departements/Gard.qmd
    - Departements/Gers.qmd
    - Haute-Garonne.qmd
    - Departements/Hautes-Pyrenees.qmd
    - Departements/Herault.qmd
    - Departements/Lot.qmd
    - Departements/Lozere.qmd
    - Departements/Pyrenees-Orientales.qmd
    - Departements/Tarn-et-Garonne.qmd
    - Departements/Tarn.qmd
    - anneeactuelle.qmd
    - villes/villes.qmd
    - meteo.qmd


website:
  repo-url: https://github.com/guibouland/GroupProject
  repo-actions: [source, issue]
  page-navigation: true
  back-to-top-navigation: true
  title: "Pollution en Occitanie"
  navbar:
    search: true
    tools: 
      - icon: github
        href: https://github.com/guibouland/GroupProject
        text: GitHub
    left:
      - href: index.qmd
        text: Carte 
      - text: "Départements"
        menu:
          - Departements/Ariege.qmd
          - Departements/Aude.qmd
          - Departements/Aveyron.qmd
          - Departements/Gard.qmd
          - Departements/Gers.qmd
          - Haute-Garonne.qmd
          - Departements/Hautes-Pyrenees.qmd
          - Departements/Herault.qmd
          - Departements/Lot.qmd
          - Departements/Lozere.qmd
          - Departements/Pyrenees-Orientales.qmd
          - Departements/Tarn-et-Garonne.qmd
          - Departements/Tarn.qmd
      - href: anneeactuelle.qmd
        text: "Évolution de la pollution"
      - villes/villes.qmd
      - meteo.qmd
      - href: about.qmd
        text: À propos
      



format:
  html:
    theme:
      dark: [cosmo, customdark.scss]
      light: [cosmo, customlight.scss]
    css: styles.css
    toc: false
    grid:
      margin-width:	175px
jupyter: python3

editor: visual




