project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - webquarto/about.qmd
    - webquarto/Departements/constatations.qmd
    - webquarto/Departements/Ariege.qmd
    - webquarto/Departements/Aveyron.qmd
    - webquarto/Departements/Gard.qmd
    - webquarto/Departements/Gers.qmd
    - webquarto/Departements/Haute-Garonne.qmd
    - webquarto/Departements/Hautes-Pyrenees.qmd
    - webquarto/Departements/Herault.qmd
    - webquarto/Departements/Pyrenees-Orientales.qmd
    - webquarto/Departements/Tarn-et-Garonne.qmd
    - webquarto/Departements/Tarn.qmd
    - webquarto/villes.qmd
    - webquarto/meteo.qmd


website:
  repo-url: https://github.com/guibouland/GroupProject
  repo-actions: [source, issue]
  page-navigation: true
  back-to-top-navigation: true
  title: "Pollution en Occitanie"
  navbar:
    search: true
    tools: 
      - icon: github
        href: https://github.com/guibouland/GroupProject
        text: GitHub
    left:
      - href: index.qmd
        text: Carte
      - text: "Départements"
        menu:
          - webquarto/Departements/constatations.qmd
          - webquarto/Departements/Ariege.qmd
          - webquarto/Departements/Aveyron.qmd
          - webquarto/Departements/Gard.qmd
          - webquarto/Departements/Gers.qmd
          - webquarto/Departements/Haute-Garonne.qmd
          - webquarto/Departements/Hautes-Pyrenees.qmd
          - webquarto/Departements/Herault.qmd
          - webquarto/Departements/Pyrenees-Orientales.qmd
          - webquarto/Departements/Tarn-et-Garonne.qmd
          - webquarto/Departements/Tarn.qmd
      - webquarto/villes.qmd
      - webquarto/meteo.qmd
      - href: webquarto/about.qmd
        text: À propos
      
format:
  html:
    theme:
      dark: [cosmo, customdark.scss]
      light: [cosmo, customlight.scss]
    css: styles.css
jupyter: python3

editor: visual




