---
title: 'Etude des graphiques'
execute:
    echo: false
format:
  html:
    toc: true
    grid:
      margin-width: 175px
---

Après analyse de tous les graphiques affichés dans les différents départements, malgré un manque partiel ou complet de données dans certains départements, on remarque quelques tendances qui semblent s'imposer.

# Oxydes d'azote NOX, NO, NO2

## Différences entre départements

Premièrement, on remarque une grande disparité concernant la quantité de pollution dans chaque département pour les polluants de type NOX/NO et NO2. Il est par conséquent compliqué de comparer les quantités d'oxydes d'azote dans les départements, mais on remarque que les stations situées proches des axes routiers semblent enregistrer des quantités bien supérieures aux autres. Cela pouvait être prédit étant donné que ces polluants résultent notamment de la combustion des carburants fossiles.
Donc les départements possédant plus de grandes villes enregistrent des quantités bien plus importantes que d'autres départements plus riverains.

## Evolution au cours de l'année

On remarque dans chaque station de chaque département, une forte hausse des quantités en hiver, quelles qu'elles soient. Cela peut être dû à une augmentation du chauffage domestique et de la production énergétique. Les concentrations chutent drastiquement à partir du mois de Mars. 

## Evolution moyenne au cours des 5 dernières années

On remarque que dans la majorité des départements, notamment dans les grandes villes, les concentrations en oxydes d'azote se réduisent légèrement. Cette évolution est moins flagrante dans les stations de campagne, cependant aux abords des routes on remarque mieux ce changement. Peut être est-ce dû à une diminution du trafic routier grâce à l'instauration de moyens de transport plus responsables notamment les transports en commun. Peut être aussi grâce aux évolutions concernant les voitures éléctriques. 
A Montpellier par exemple, la volonté de la ville est de réduire le trafic routier et de convaincre les gens d'utiliser les transports en commun, donc la ville a entreprit de grands changements avec une gratuité partielle bientôt complète des transport en commun. Probablement que ce genre de décision impacte positivement cette diminution des quantités des oxydes d'azote.

## Remarques

Au sein d'une même ville, on remarque des concentrations drastiquement différentes selon les positions des stations. Les stations proches des aéroports enregistrent par exemple des quantités bien moindre que les stations proches des axes routiers, voir la partie sur les comparaisons entre villes pour plus de détails.

# Ozone O3

## Différences entre départements

A l'inverse des oxydes d'azote, la concentration en ozone semble proche peu importe la position de la station et le département au cours de l'année. 

## Evolution au cours de l'année 

On remarque une forte diminution des concentrations en hiver, probablement due à une baisse de l'ensoleillement, puisque ce polluant résulte de la transformation d'autres polluants sous l'influence de rayonnements solaires.

## Evolution moyenne au cours des 5 dernières années

On remarque dans la majorité des départements, hormis une faible dinimution des concentrations en 2020, celles-ci restent globalement constantes.

## Remarque

Les concentrations en O3 semblent évoluer au cours de l'année symétriquement à celles en NOX. En effet cela est plutôt logique puisque le polluant O3 provient de la transformation des polluants NOX sous l'effet des rayonnements solaires. Il pourrait être intéressant de comparer l'évolution de la somme des polluants au cours de l'année dans chaque département pour observer l'évolution de celle-ci.

# Particules en suspension

## Différences entre départements

Les concentrations en particules semblent propres à chaque département, cependant les quantités restent globalement toujours entre 10 et 30 (ug.m-3). En effet les concentrations peuvent être 2 fois supérieures dans les villes qu'en campagne, cependant on observe quand même une tendance assez marquée dans chaque département.

## Evolution moyenne au cours des 5 dernières années

Les concentrations semblent constantes au cours des dernières années. On remarque une évolution très faible au cours des 5 ans, qui n'a de tendance ni positive ni négative.