# Projet Groupe 4
# Projet Groupe Pollution en Occitanie groupe 4
## Environnement
Pour ce projet, nous allons avoir besoin d'un environnement contenant:
- Python
- Pandas
- Plotly
- Pytest
- Pooch

## Objectif
L'objectif est de créer un site contenant une carte interactive permettant de voir la pollution en occitannie à une période donnée. Cette carte devra être lisible et facilement interprétable.\
Les données sont extraites du site [Atmo Occitanie](https://data-atmo-occitanie.opendata.arcgis.com/pages/liste-des-flux) et concerneront la pollution de l'air, notamment les particules en suspension, les particules fines et le dioxyde d'azote.\
## Feuille de route
Pour atteindre notre objectif, nous avons divisé le travail de la facon suivante: 
### Diagramme de Gantt
```{mermaid}
    gantt
        dateFormat YYYY-MM-DD
        title Diagramme de Gantt pour les avancées du projet
        
        %% Ceci est provisoire
        section Pierre
            familiatisation avec quarto  : done,     2023-10-01, 2023-10-07
            création de l'ébauche du site : done,   2023-10-07, 2023-10-14
            Programmation : active,         2023-10-23, 2023-12-10
            Aspect interactif de la carte : crit,         2023-10-14, 2023-12-10
            Rendre la carte cliquable par departements : crit,  2023-10-14, 2023-10-28
            Pollution sur les cartes selon légende : crit, 2023-10-28, 2023-11-18
            
        section Guillaume
            Recherche concernant le projet  : done,     2023-10-01, 2023-10-23
            Programmation : active,         2023-10-23, 2023-12-10
            Elaboration du site : crit,         2023-10-23, 2023-12-10
            
        section Maxence
            Recherche concernant le projet : done,     2023-10-01, 2023-10-23
            Programmation : active,         2023-10-23, 2023-12-10
            Création des classes : crit,         2023-10-23, 2023-11-10
            
        section Quentin
            Recherche concernant le projet : done,     2023-10-01, 2023-10-23
            Programmation : active,         2023-10-23, 2023-12-10
            Sélection des données : crit,         2023-10-23, 2023-11-10
            Utilisation/interprétation des données : crit,         2023-11-10, 2023-12-10
        section Groupe
            Préparation de la presentation orale avec slides sur Quarto : crit, 2023-11-18, 2023-12-10
        
        section Evaluation
            Présentation projet : active, milestone,     2023-10-23, 2023-10-23
            Dépôt projet : milestone,     2023-12-10, 2023-12-10
            Présentation orale : milestone,     2023-12-15, 2023-12-15

```
### Branches
Pour ne pas déranger nos travaux respectifs, nous feront évoluer le projet à l'aide de plusieurs branches:
- "site" qui sera attribuée à toutes les modifications concernant le site,
- "plot" specifique aux graphiques,
- "carte" pour manipuler celles-ci
### Visuel
> Photo du dessin
## Site Web
Le site internet (maintenant qu'il marche) de ce projet est disponible à l'URL suivante: [https://guibouland.github.io/GroupProject](https://guibouland.github.io/GroupProject/)

## Choix des données
Les données du site [Atmo Occitanie](https://data-atmo-occitanie.opendata.arcgis.com/pages/liste-des-flux) sont nombreuses et ne nous seront pas toutes utiles. Nous allons donc utiliser les suivantes:
- Les données de 2020
- Les données d'il y a 5 ans

## Diagramme de Gantt



